import React from 'react';
import { Icon } from 'antd';
import './demo.scss';


const Section = () => {
  return(
    <section>

<h3 id="Directional-Icons"><span>Directional Icons</span></h3>
<ul className="anticons-list clearfix icons">
<li className=""><Icon type="step-backward" /><span className="anticon-class"><span className="ant-badge">step-backward</span></span></li>
<li className=""><Icon type="step-forward" /><span className="anticon-class"><span className="ant-badge">step-forward</span></span></li>
<li className=""><Icon type="fast-backward" /><span className="anticon-class"><span className="ant-badge">fast-backward</span></span></li>
<li className=""><Icon type="fast-forward" /><span className="anticon-class"><span className="ant-badge">fast-forward</span></span></li>
<li className=""><Icon type="shrink" /><span className="anticon-class"><span className="ant-badge">shrink</span></span></li>
<li className=""><Icon type="arrows-alt" /><span className="anticon-class"><span className="ant-badge">arrows-alt</span></span></li>
<li className=""><Icon type="down" /><span className="anticon-class"><span className="ant-badge">down</span></span></li>
<li className=""><Icon type="up" /><span className="anticon-class"><span className="ant-badge">up</span></span></li>
<li className=""><Icon type="left" /><span className="anticon-class"><span className="ant-badge">left</span></span></li>
<li className=""><Icon type="right" /><span className="anticon-class"><span className="ant-badge">right</span></span></li>
<li className=""><Icon type="caret-up" /><span className="anticon-class"><span className="ant-badge">caret-up</span></span></li>
<li className=""><Icon type="caret-down" /><span className="anticon-class"><span className="ant-badge">caret-down</span></span></li>
<li className=""><Icon type="caret-left" /><span className="anticon-class"><span className="ant-badge">caret-left</span></span></li>
<li className=""><Icon type="caret-right" /><span className="anticon-class"><span className="ant-badge">caret-right</span></span></li>
<li className=""><Icon type="up-circle" /><span className="anticon-class"><span className="ant-badge">up-circle</span></span></li>
<li className=""><Icon type="down-circle" /><span className="anticon-class"><span className="ant-badge">down-circle</span></span></li>
<li className=""><Icon type="left-circle" /><span className="anticon-class"><span className="ant-badge">left-circle</span></span></li>
<li className=""><Icon type="right-circle" /><span className="anticon-class"><span className="ant-badge">right-circle</span></span></li>
<li className=""><Icon type="up-circle-o" /><span className="anticon-class"><span className="ant-badge">up-circle-o</span></span></li>
<li className=""><Icon type="down-circle-o" /><span className="anticon-class"><span className="ant-badge">down-circle-o</span></span></li>
<li className=""><Icon type="right-circle-o" /><span className="anticon-class"><span className="ant-badge">right-circle-o</span></span></li>
<li className=""><Icon type="left-circle-o" /><span className="anticon-class"><span className="ant-badge">left-circle-o</span></span></li>
<li className=""><Icon type="double-right" /><span className="anticon-class"><span className="ant-badge">double-right</span></span></li>
<li className=""><Icon type="double-left" /><span className="anticon-class"><span className="ant-badge">double-left</span></span></li>
<li className=""><Icon type="verticle-left" /><span className="anticon-class"><span className="ant-badge">verticle-left</span></span></li>
<li className=""><Icon type="verticle-right" /><span className="anticon-class"><span className="ant-badge">verticle-right</span></span></li>
<li className=""><Icon type="forward" /><span className="anticon-class"><span className="ant-badge">forward</span></span></li>
<li className=""><Icon type="backward" /><span className="anticon-class"><span className="ant-badge">backward</span></span></li>
<li className=""><Icon type="rollback" /><span className="anticon-class"><span className="ant-badge">rollback</span></span></li>
<li className=""><Icon type="enter" /><span className="anticon-class"><span className="ant-badge">enter</span></span></li>
<li className=""><Icon type="retweet" /><span className="anticon-class"><span className="ant-badge">retweet</span></span></li>
<li className=""><Icon type="swap" /><span className="anticon-class"><span className="ant-badge">swap</span></span></li>
<li className=""><Icon type="swap-left" /><span className="anticon-class"><span className="ant-badge">swap-left</span></span></li>
<li className=""><Icon type="swap-right" /><span className="anticon-class"><span className="ant-badge">swap-right</span></span></li>
<li className=""><Icon type="arrow-up" /><span className="anticon-class"><span className="ant-badge">arrow-up</span></span></li>
<li className=""><Icon type="arrow-down" /><span className="anticon-class"><span className="ant-badge">arrow-down</span></span></li>
<li className=""><Icon type="arrow-left" /><span className="anticon-class"><span className="ant-badge">arrow-left</span></span></li>
<li className=""><Icon type="arrow-right" /><span className="anticon-class"><span className="ant-badge">arrow-right</span></span></li>
<li className=""><Icon type="play-circle" /><span className="anticon-class"><span className="ant-badge">play-circle</span></span></li>
<li className=""><Icon type="play-circle-o" /><span className="anticon-class"><span className="ant-badge">play-circle-o</span></span></li>
<li className=""><Icon type="up-square" /><span className="anticon-class"><span className="ant-badge">up-square</span></span></li>
<li className=""><Icon type="down-square" /><span className="anticon-class"><span className="ant-badge">down-square</span></span></li>
<li className=""><Icon type="left-square" /><span className="anticon-class"><span className="ant-badge">left-square</span></span></li>
<li className=""><Icon type="right-square" /><span className="anticon-class"><span className="ant-badge">right-square</span></span></li>
<li className=""><Icon type="up-square-o" /><span className="anticon-class"><span className="ant-badge">up-square-o</span></span></li>
<li className=""><Icon type="down-square-o" /><span className="anticon-class"><span className="ant-badge">down-square-o</span></span></li>
<li className=""><Icon type="left-square-o" /><span className="anticon-class"><span className="ant-badge">left-square-o</span></span></li>
<li className=""><Icon type="right-square-o" /><span className="anticon-class"><span className="ant-badge">right-square-o</span></span></li>
<li className=""><Icon type="login" /><span className="anticon-class"><span className="ant-badge">login</span></span></li>
<li className=""><Icon type="logout" /><span className="anticon-class"><span className="ant-badge">logout</span></span></li>
<li className=""><Icon type="menu-fold" /><span className="anticon-class"><span className="ant-badge">menu-fold</span></span></li>
<li className=""><Icon type="menu-unfold" /><span className="anticon-class"><span className="ant-badge">menu-unfold</span></span></li>
</ul>

<h3 id="Suggested-Icons"><span>Suggested Icons</span></h3>
<ul className="anticons-list clearfix icons">
<li className=""><Icon type="question" /><span className="anticon-class"><span className="ant-badge">question</span></span></li>
<li className=""><Icon type="question-circle-o" /><span className="anticon-class"><span className="ant-badge">question-circle-o</span></span></li>
<li className=""><Icon type="question-circle" /><span className="anticon-class"><span className="ant-badge">question-circle</span></span></li>
<li className=""><Icon type="plus" /><span className="anticon-class"><span className="ant-badge">plus</span></span></li>
<li className=""><Icon type="plus-circle-o" /><span className="anticon-class"><span className="ant-badge">plus-circle-o</span></span></li>
<li className=""><Icon type="plus-circle" /><span className="anticon-class"><span className="ant-badge">plus-circle</span></span></li>
<li className=""><Icon type="pause" /><span className="anticon-class"><span className="ant-badge">pause</span></span></li>
<li className=""><Icon type="pause-circle-o" /><span className="anticon-class"><span className="ant-badge">pause-circle-o</span></span></li>
<li className=""><Icon type="pause-circle" /><span className="anticon-class"><span className="ant-badge">pause-circle</span></span></li>
<li className=""><Icon type="minus" /><span className="anticon-class"><span className="ant-badge">minus</span></span></li>
<li className=""><Icon type="minus-circle-o" /><span className="anticon-class"><span className="ant-badge">minus-circle-o</span></span></li>
<li className=""><Icon type="minus-circle" /><span className="anticon-class"><span className="ant-badge">minus-circle</span></span></li>
<li className=""><Icon type="plus-square" /><span className="anticon-class"><span className="ant-badge">plus-square</span></span></li>
<li className=""><Icon type="plus-square-o" /><span className="anticon-class"><span className="ant-badge">plus-square-o</span></span></li>
<li className=""><Icon type="minus-square" /><span className="anticon-class"><span className="ant-badge">minus-square</span></span></li>
<li className=""><Icon type="minus-square-o" /><span className="anticon-class"><span className="ant-badge">minus-square-o</span></span></li>
<li className=""><Icon type="info" /><span className="anticon-class"><span className="ant-badge">info</span></span></li>
<li className=""><Icon type="info-circle-o" /><span className="anticon-class"><span className="ant-badge">info-circle-o</span></span></li>
<li className=""><Icon type="info-circle" /><span className="anticon-class"><span className="ant-badge">info-circle</span></span></li>
<li className=""><Icon type="exclamation" /><span className="anticon-class"><span className="ant-badge">exclamation</span></span></li>
<li className=""><Icon type="exclamation-circle-o" /><span className="anticon-class"><span className="ant-badge">exclamation-circle-o</span></span></li>
<li className=""><Icon type="exclamation-circle" /><span className="anticon-class"><span className="ant-badge">exclamation-circle</span></span></li>
<li className=""><Icon type="close" /><span className="anticon-class"><span className="ant-badge">close</span></span></li>
<li className=""><Icon type="close-circle" /><span className="anticon-class"><span className="ant-badge">close-circle</span></span></li>
<li className=""><Icon type="close-circle-o" /><span className="anticon-class"><span className="ant-badge">close-circle-o</span></span></li>
<li className=""><Icon type="close-square" /><span className="anticon-class"><span className="ant-badge">close-square</span></span></li>
<li className=""><Icon type="close-square-o" /><span className="anticon-class"><span className="ant-badge">close-square-o</span></span></li>
<li className=""><Icon type="check" /><span className="anticon-class"><span className="ant-badge">check</span></span></li>
<li className=""><Icon type="check-circle" /><span className="anticon-class"><span className="ant-badge">check-circle</span></span></li>
<li className=""><Icon type="check-circle-o" /><span className="anticon-class"><span className="ant-badge">check-circle-o</span></span></li>
<li className=""><Icon type="check-square" /><span className="anticon-class"><span className="ant-badge">check-square</span></span></li>
<li className=""><Icon type="check-square-o" /><span className="anticon-class"><span className="ant-badge">check-square-o</span></span></li>
<li className=""><Icon type="clock-circle-o" /><span className="anticon-class"><span className="ant-badge">clock-circle-o</span></span></li>
<li className=""><Icon type="clock-circle" /><span className="anticon-class"><span className="ant-badge">clock-circle</span></span></li>
<li className=""><Icon type="warning" /><span className="anticon-class"><span className="ant-badge">warning</span></span></li>
</ul>

<h3 id="Application-Icons"><span>Application Icons</span></h3>
<ul className="anticons-list clearfix icons">
<li className=""><Icon type="lock" /><span className="anticon-class"><span className="ant-badge">lock</span></span></li>
<li className=""><Icon type="unlock" /><span className="anticon-class"><span className="ant-badge">unlock</span></span></li>
<li className=""><Icon type="area-chart" /><span className="anticon-class"><span className="ant-badge">area-chart</span></span></li>
<li className=""><Icon type="pie-chart" /><span className="anticon-class"><span className="ant-badge">pie-chart</span></span></li>
<li className=""><Icon type="bar-chart" /><span className="anticon-class"><span className="ant-badge">bar-chart</span></span></li>
<li className=""><Icon type="dot-chart" /><span className="anticon-class"><span className="ant-badge">dot-chart</span></span></li>
<li className=""><Icon type="bars" /><span className="anticon-class"><span className="ant-badge">bars</span></span></li>
<li className=""><Icon type="book" /><span className="anticon-class"><span className="ant-badge">book</span></span></li>
<li className=""><Icon type="calendar" /><span className="anticon-class"><span className="ant-badge">calendar</span></span></li>
<li className=""><Icon type="cloud" /><span className="anticon-class"><span className="ant-badge">cloud</span></span></li>
<li className=""><Icon type="cloud-download" /><span className="anticon-class"><span className="ant-badge">cloud-download</span></span></li>
<li className=""><Icon type="code" /><span className="anticon-class"><span className="ant-badge">code</span></span></li>
<li className=""><Icon type="code-o" /><span className="anticon-class"><span className="ant-badge">code-o</span></span></li>
<li className=""><Icon type="copy" /><span className="anticon-class"><span className="ant-badge">copy</span></span></li>
<li className=""><Icon type="credit-card" /><span className="anticon-class"><span className="ant-badge">credit-card</span></span></li>
<li className=""><Icon type="delete" /><span className="anticon-class"><span className="ant-badge">delete</span></span></li>
<li className=""><Icon type="desktop" /><span className="anticon-class"><span className="ant-badge">desktop</span></span></li>
<li className=""><Icon type="download" /><span className="anticon-class"><span className="ant-badge">download</span></span></li>
<li className=""><Icon type="edit" /><span className="anticon-class"><span className="ant-badge">edit</span></span></li>
<li className=""><Icon type="ellipsis" /><span className="anticon-class"><span className="ant-badge">ellipsis</span></span></li>
<li className=""><Icon type="file" /><span className="anticon-class"><span className="ant-badge">file</span></span></li>
<li className=""><Icon type="file-text" /><span className="anticon-class"><span className="ant-badge">file-text</span></span></li>
<li className=""><Icon type="file-unknown" /><span className="anticon-class"><span className="ant-badge">file-unknown</span></span></li>
<li className=""><Icon type="file-pdf" /><span className="anticon-class"><span className="ant-badge">file-pdf</span></span></li>
<li className=""><Icon type="file-word" /><span className="anticon-class"><span className="ant-badge">file-word</span></span></li>
<li className=""><Icon type="file-excel" /><span className="anticon-class"><span className="ant-badge">file-excel</span></span></li>
<li className=""><Icon type="file-jpg" /><span className="anticon-class"><span className="ant-badge">file-jpg</span></span></li>
<li className=""><Icon type="file-ppt" /><span className="anticon-class"><span className="ant-badge">file-ppt</span></span></li>
<li className=""><Icon type="file-markdown" /><span className="anticon-class"><span className="ant-badge">file-markdown</span></span></li>
<li className=""><Icon type="file-add" /><span className="anticon-class"><span className="ant-badge">file-add</span></span></li>
<li className=""><Icon type="folder" /><span className="anticon-class"><span className="ant-badge">folder</span></span></li>
<li className=""><Icon type="folder-open" /><span className="anticon-class"><span className="ant-badge">folder-open</span></span></li>
<li className=""><Icon type="folder-add" /><span className="anticon-class"><span className="ant-badge">folder-add</span></span></li>
<li className=""><Icon type="hdd" /><span className="anticon-class"><span className="ant-badge">hdd</span></span></li>
<li className=""><Icon type="frown" /><span className="anticon-class"><span className="ant-badge">frown</span></span></li>
<li className=""><Icon type="frown-o" /><span className="anticon-class"><span className="ant-badge">frown-o</span></span></li>
<li className=""><Icon type="meh" /><span className="anticon-class"><span className="ant-badge">meh</span></span></li>
<li className=""><Icon type="meh-o" /><span className="anticon-class"><span className="ant-badge">meh-o</span></span></li>
<li className=""><Icon type="smile" /><span className="anticon-class"><span className="ant-badge">smile</span></span></li>
<li className=""><Icon type="smile-o" /><span className="anticon-class"><span className="ant-badge">smile-o</span></span></li>
<li className=""><Icon type="inbox" /><span className="anticon-class"><span className="ant-badge">inbox</span></span></li>
<li className=""><Icon type="laptop" /><span className="anticon-class"><span className="ant-badge">laptop</span></span></li>
<li className=""><Icon type="appstore-o" /><span className="anticon-class"><span className="ant-badge">appstore-o</span></span></li>
<li className=""><Icon type="appstore" /><span className="anticon-class"><span className="ant-badge">appstore</span></span></li>
<li className=""><Icon type="line-chart" /><span className="anticon-class"><span className="ant-badge">line-chart</span></span></li>
<li className=""><Icon type="link" /><span className="anticon-class"><span className="ant-badge">link</span></span></li>
<li className=""><Icon type="mail" /><span className="anticon-class"><span className="ant-badge">mail</span></span></li>
<li className=""><Icon type="mobile" /><span className="anticon-class"><span className="ant-badge">mobile</span></span></li>
<li className=""><Icon type="notification" /><span className="anticon-class"><span className="ant-badge">notification</span></span></li>
<li className=""><Icon type="paper-clip" /><span className="anticon-class"><span className="ant-badge">paper-clip</span></span></li>
<li className=""><Icon type="picture" /><span className="anticon-class"><span className="ant-badge">picture</span></span></li>
<li className=""><Icon type="poweroff" /><span className="anticon-class"><span className="ant-badge">poweroff</span></span></li>
<li className=""><Icon type="reload" /><span className="anticon-class"><span className="ant-badge">reload</span></span></li>
<li className=""><Icon type="search" /><span className="anticon-class"><span className="ant-badge">search</span></span></li>
<li className=""><Icon type="setting" /><span className="anticon-class"><span className="ant-badge">setting</span></span></li>
<li className=""><Icon type="share-alt" /><span className="anticon-class"><span className="ant-badge">share-alt</span></span></li>
<li className=""><Icon type="shopping-cart" /><span className="anticon-class"><span className="ant-badge">shopping-cart</span></span></li>
<li className=""><Icon type="tablet" /><span className="anticon-class"><span className="ant-badge">tablet</span></span></li>
<li className=""><Icon type="tag" /><span className="anticon-class"><span className="ant-badge">tag</span></span></li>
<li className=""><Icon type="tag-o" /><span className="anticon-class"><span className="ant-badge">tag-o</span></span></li>
<li className=""><Icon type="tags" /><span className="anticon-class"><span className="ant-badge">tags</span></span></li>
<li className=""><Icon type="tags-o" /><span className="anticon-class"><span className="ant-badge">tags-o</span></span></li>
<li className=""><Icon type="to-top" /><span className="anticon-class"><span className="ant-badge">to-top</span></span></li>
<li className=""><Icon type="upload" /><span className="anticon-class"><span className="ant-badge">upload</span></span></li>
<li className=""><Icon type="user" /><span className="anticon-class"><span className="ant-badge">user</span></span></li>
<li className=""><Icon type="video-camera" /><span className="anticon-class"><span className="ant-badge">video-camera</span></span></li>
<li className=""><Icon type="home" /><span className="anticon-class"><span className="ant-badge">home</span></span></li>
<li className=""><Icon type="spin anticon-loading" /><span className="anticon-class"><span className="ant-badge">loading</span></span></li>
<li className=""><Icon type="loading-3-quarters" /><span className="anticon-class"><span className="ant-badge">loading-3-quarters</span></span></li>
<li className=""><Icon type="cloud-upload-o" /><span className="anticon-class"><span className="ant-badge">cloud-upload-o</span></span></li>
<li className=""><Icon type="cloud-download-o" /><span className="anticon-class"><span className="ant-badge">cloud-download-o</span></span></li>
<li className=""><Icon type="cloud-upload" /><span className="anticon-class"><span className="ant-badge">cloud-upload</span></span></li>
<li className=""><Icon type="cloud-o" /><span className="anticon-class"><span className="ant-badge">cloud-o</span></span></li>
<li className=""><Icon type="star-o" /><span className="anticon-class"><span className="ant-badge">star-o</span></span></li>
<li className=""><Icon type="star" /><span className="anticon-class"><span className="ant-badge">star</span></span></li>
<li className=""><Icon type="heart-o" /><span className="anticon-class"><span className="ant-badge">heart-o</span></span></li>
<li className=""><Icon type="heart" /><span className="anticon-class"><span className="ant-badge">heart</span></span></li>
<li className=""><Icon type="environment" /><span className="anticon-class"><span className="ant-badge">environment</span></span></li>
<li className=""><Icon type="environment-o" /><span className="anticon-class"><span className="ant-badge">environment-o</span></span></li>
<li className=""><Icon type="eye" /><span className="anticon-class"><span className="ant-badge">eye</span></span></li>
<li className=""><Icon type="eye-o" /><span className="anticon-class"><span className="ant-badge">eye-o</span></span></li>
<li className=""><Icon type="camera" /><span className="anticon-class"><span className="ant-badge">camera</span></span></li>
<li className=""><Icon type="camera-o" /><span className="anticon-class"><span className="ant-badge">camera-o</span></span></li>
<li className=""><Icon type="save" /><span className="anticon-class"><span className="ant-badge">save</span></span></li>
<li className=""><Icon type="team" /><span className="anticon-class"><span className="ant-badge">team</span></span></li>
<li className=""><Icon type="solution" /><span className="anticon-class"><span className="ant-badge">solution</span></span></li>
<li className=""><Icon type="phone" /><span className="anticon-class"><span className="ant-badge">phone</span></span></li>
<li className=""><Icon type="filter" /><span className="anticon-class"><span className="ant-badge">filter</span></span></li>
<li className=""><Icon type="exception" /><span className="anticon-class"><span className="ant-badge">exception</span></span></li>
<li className=""><Icon type="export" /><span className="anticon-class"><span className="ant-badge">export</span></span></li>
<li className=""><Icon type="customer-service" /><span className="anticon-class"><span className="ant-badge">customer-service</span></span></li>
<li className=""><Icon type="qrcode" /><span className="anticon-class"><span className="ant-badge">qrcode</span></span></li>
<li className=""><Icon type="scan" /><span className="anticon-class"><span className="ant-badge">scan</span></span></li>
<li className=""><Icon type="like" /><span className="anticon-class"><span className="ant-badge">like</span></span></li>
<li className=""><Icon type="like-o" /><span className="anticon-class"><span className="ant-badge">like-o</span></span></li>
<li className=""><Icon type="dislike" /><span className="anticon-class"><span className="ant-badge">dislike</span></span></li>
<li className=""><Icon type="dislike-o" /><span className="anticon-class"><span className="ant-badge">dislike-o</span></span></li>
<li className=""><Icon type="message" /><span className="anticon-class"><span className="ant-badge">message</span></span></li>
<li className=""><Icon type="pay-circle" /><span className="anticon-class"><span className="ant-badge">pay-circle</span></span></li>
<li className=""><Icon type="pay-circle-o" /><span className="anticon-class"><span className="ant-badge">pay-circle-o</span></span></li>
<li className=""><Icon type="calculator" /><span className="anticon-class"><span className="ant-badge">calculator</span></span></li>
<li className=""><Icon type="pushpin" /><span className="anticon-class"><span className="ant-badge">pushpin</span></span></li>
<li className=""><Icon type="pushpin-o" /><span className="anticon-class"><span className="ant-badge">pushpin-o</span></span></li>
<li className=""><Icon type="bulb" /><span className="anticon-class"><span className="ant-badge">bulb</span></span></li>
<li className=""><Icon type="select" /><span className="anticon-class"><span className="ant-badge">select</span></span></li>
<li className=""><Icon type="switcher" /><span className="anticon-class"><span className="ant-badge">switcher</span></span></li>
<li className=""><Icon type="rocket" /><span className="anticon-class"><span className="ant-badge">rocket</span></span></li>
<li className=""><Icon type="bell" /><span className="anticon-class"><span className="ant-badge">bell</span></span></li>
<li className=""><Icon type="disconnect" /><span className="anticon-class"><span className="ant-badge">disconnect</span></span></li>
<li className=""><Icon type="database" /><span className="anticon-class"><span className="ant-badge">database</span></span></li>
<li className=""><Icon type="compass" /><span className="anticon-class"><span className="ant-badge">compass</span></span></li>
<li className=""><Icon type="barcode" /><span className="anticon-class"><span className="ant-badge">barcode</span></span></li>
<li className=""><Icon type="hourglass" /><span className="anticon-class"><span className="ant-badge">hourglass</span></span></li>
<li className=""><Icon type="key" /><span className="anticon-class"><span className="ant-badge">key</span></span></li>
<li className=""><Icon type="flag" /><span className="anticon-class"><span className="ant-badge">flag</span></span></li>
<li className=""><Icon type="layout" /><span className="anticon-class"><span className="ant-badge">layout</span></span></li>
<li className=""><Icon type="printer" /><span className="anticon-class"><span className="ant-badge">printer</span></span></li>
<li className=""><Icon type="sound" /><span className="anticon-class"><span className="ant-badge">sound</span></span></li>
<li className=""><Icon type="usb" /><span className="anticon-class"><span className="ant-badge">usb</span></span></li>
<li className=""><Icon type="skin" /><span className="anticon-class"><span className="ant-badge">skin</span></span></li>
<li className=""><Icon type="tool" /><span className="anticon-class"><span className="ant-badge">tool</span></span></li>
<li className=""><Icon type="sync" /><span className="anticon-class"><span className="ant-badge">sync</span></span></li>
<li className=""><Icon type="wifi" /><span className="anticon-class"><span className="ant-badge">wifi</span></span></li>
<li className=""><Icon type="car" /><span className="anticon-class"><span className="ant-badge">car</span></span></li>
<li className=""><Icon type="schedule" /><span className="anticon-class"><span className="ant-badge">schedule</span></span></li>
<li className=""><Icon type="user-add" /><span className="anticon-class"><span className="ant-badge">user-add</span></span></li>
<li className=""><Icon type="user-delete" /><span className="anticon-class"><span className="ant-badge">user-delete</span></span></li>
<li className=""><Icon type="usergroup-add" /><span className="anticon-class"><span className="ant-badge">usergroup-add</span></span></li>
<li className=""><Icon type="usergroup-delete" /><span className="anticon-class"><span className="ant-badge">usergroup-delete</span></span></li>
<li className=""><Icon type="man" /><span className="anticon-class"><span className="ant-badge">man</span></span></li>
<li className=""><Icon type="woman" /><span className="anticon-class"><span className="ant-badge">woman</span></span></li>
<li className=""><Icon type="shop" /><span className="anticon-class"><span className="ant-badge">shop</span></span></li>
<li className=""><Icon type="gift" /><span className="anticon-class"><span className="ant-badge">gift</span></span></li>
<li className=""><Icon type="idcard" /><span className="anticon-class"><span className="ant-badge">idcard</span></span></li>
<li className=""><Icon type="medicine-box" /><span className="anticon-class"><span className="ant-badge">medicine-box</span></span></li>
<li className=""><Icon type="red-envelope" /><span className="anticon-class"><span className="ant-badge">red-envelope</span></span></li>
<li className=""><Icon type="coffee" /><span className="anticon-class"><span className="ant-badge">coffee</span></span></li>
<li className=""><Icon type="copyright" /><span className="anticon-class"><span className="ant-badge">copyright</span></span></li>
<li className=""><Icon type="trademark" /><span className="anticon-class"><span className="ant-badge">trademark</span></span></li>
<li className=""><Icon type="safety" /><span className="anticon-class"><span className="ant-badge">safety</span></span></li>
<li className=""><Icon type="wallet" /><span className="anticon-class"><span className="ant-badge">wallet</span></span></li>
<li className=""><Icon type="bank" /><span className="anticon-class"><span className="ant-badge">bank</span></span></li>
<li className=""><Icon type="trophy" /><span className="anticon-class"><span className="ant-badge">trophy</span></span></li>
<li className=""><Icon type="contacts" /><span className="anticon-class"><span className="ant-badge">contacts</span></span></li>
<li className=""><Icon type="global" /><span className="anticon-class"><span className="ant-badge">global</span></span></li>
<li className=""><Icon type="shake" /><span className="anticon-class"><span className="ant-badge">shake</span></span></li>
<li className=""><Icon type="api" /><span className="anticon-class"><span className="ant-badge">api</span></span></li>
<li className=""><Icon type="fork" /><span className="anticon-class"><span className="ant-badge">fork</span></span></li>
<li className=""><Icon type="dashboard" /><span className="anticon-class"><span className="ant-badge">dashboard</span></span></li>
<li className=""><Icon type="form" /><span className="anticon-class"><span className="ant-badge">form</span></span></li>
<li className=""><Icon type="table" /><span className="anticon-class"><span className="ant-badge">table</span></span></li>
<li className=""><Icon type="profile" /><span className="anticon-class"><span className="ant-badge">profile</span></span></li>
</ul>

<h3 id="Brand-and-Logos"><span>Brand and Logos</span></h3>
<ul className="anticons-list clearfix icons">
<li className=""><Icon type="android" /><span className="anticon-class"><span className="ant-badge">android</span></span></li>
<li className=""><Icon type="android-o" /><span className="anticon-class"><span className="ant-badge">android-o</span></span></li>
<li className=""><Icon type="apple" /><span className="anticon-class"><span className="ant-badge">apple</span></span></li>
<li className=""><Icon type="apple-o" /><span className="anticon-class"><span className="ant-badge">apple-o</span></span></li>
<li className=""><Icon type="windows" /><span className="anticon-class"><span className="ant-badge">windows</span></span></li>
<li className=""><Icon type="windows-o" /><span className="anticon-class"><span className="ant-badge">windows-o</span></span></li>
<li className=""><Icon type="ie" /><span className="anticon-class"><span className="ant-badge">ie</span></span></li>
<li className=""><Icon type="chrome" /><span className="anticon-class"><span className="ant-badge">chrome</span></span></li>
<li className=""><Icon type="github" /><span className="anticon-class"><span className="ant-badge">github</span></span></li>
<li className=""><Icon type="aliwangwang" /><span className="anticon-class"><span className="ant-badge">aliwangwang</span></span></li>
<li className=""><Icon type="aliwangwang-o" /><span className="anticon-class"><span className="ant-badge">aliwangwang-o</span></span></li>
<li className=""><Icon type="dingding" /><span className="anticon-class"><span className="ant-badge">dingding</span></span></li>
<li className=""><Icon type="dingding-o" /><span className="anticon-class"><span className="ant-badge">dingding-o</span></span></li>
<li className=""><Icon type="weibo-square" /><span className="anticon-class"><span className="ant-badge">weibo-square</span></span></li>
<li className=""><Icon type="weibo-circle" /><span className="anticon-class"><span className="ant-badge">weibo-circle</span></span></li>
<li className=""><Icon type="taobao-circle" /><span className="anticon-class"><span className="ant-badge">taobao-circle</span></span></li>
<li className=""><Icon type="html5" /><span className="anticon-class"><span className="ant-badge">html5</span></span></li>
<li className=""><Icon type="weibo" /><span className="anticon-class"><span className="ant-badge">weibo</span></span></li>
<li className=""><Icon type="twitter" /><span className="anticon-class"><span className="ant-badge">twitter</span></span></li>
<li className=""><Icon type="wechat" /><span className="anticon-class"><span className="ant-badge">wechat</span></span></li>
<li className=""><Icon type="youtube" /><span className="anticon-class"><span className="ant-badge">youtube</span></span></li>
<li className=""><Icon type="alipay-circle" /><span className="anticon-class"><span className="ant-badge">alipay-circle</span></span></li>
<li className=""><Icon type="taobao" /><span className="anticon-class"><span className="ant-badge">taobao</span></span></li>
<li className=""><Icon type="skype" /><span className="anticon-class"><span className="ant-badge">skype</span></span></li>
<li className=""><Icon type="qq" /><span className="anticon-class"><span className="ant-badge">qq</span></span></li>
<li className=""><Icon type="medium-workmark" /><span className="anticon-class"><span className="ant-badge">medium-workmark</span></span></li>
<li className=""><Icon type="gitlab" /><span className="anticon-class"><span className="ant-badge">gitlab</span></span></li>
<li className=""><Icon type="medium" /><span className="anticon-class"><span className="ant-badge">medium</span></span></li>
<li className=""><Icon type="linkedin" /><span className="anticon-class"><span className="ant-badge">linkedin</span></span></li>
<li className=""><Icon type="google-plus" /><span className="anticon-class"><span className="ant-badge">google-plus</span></span></li>
<li className=""><Icon type="dropbox" /><span className="anticon-class"><span className="ant-badge">dropbox</span></span></li>
<li className=""><Icon type="facebook" theme="filled" /><span className="anticon-class"><span className="ant-badge">facebook</span></span></li>
<li className=""><Icon type="codepen" /><span className="anticon-class"><span className="ant-badge">codepen</span></span></li>
<li className=""><Icon type="amazon" /><span className="anticon-class"><span className="ant-badge">amazon</span></span></li>
<li className=""><Icon type="google" /><span className="anticon-class"><span className="ant-badge">google</span></span></li>
<li className=""><Icon type="codepen-circle" /><span className="anticon-class"><span className="ant-badge">codepen-circle</span></span></li>
<li className=""><Icon type="alipay" /><span className="anticon-class"><span className="ant-badge">alipay</span></span></li>
<li className=""><Icon type="ant-design" /><span className="anticon-class"><span className="ant-badge">ant-design</span></span></li>
<li className=""><Icon type="aliyun" /><span className="anticon-class"><span className="ant-badge">aliyun</span></span></li>
<li className=""><Icon type="zhihu" /><span className="anticon-class"><span className="ant-badge">zhihu</span></span></li>
<li className=""><Icon type="slack" /><span className="anticon-class"><span className="ant-badge">slack</span></span></li>
<li className=""><Icon type="slack-square" /><span className="anticon-class"><span className="ant-badge">slack-square</span></span></li>
<li className=""><Icon type="behance" /><span className="anticon-class"><span className="ant-badge">behance</span></span></li>
<li className=""><Icon type="behance-square" /><span className="anticon-class"><span className="ant-badge">behance-square</span></span></li>
<li className=""><Icon type="dribbble" /><span className="anticon-class"><span className="ant-badge">dribbble</span></span></li>
<li className=""><Icon type="dribbble-square" /><span className="anticon-class"><span className="ant-badge">dribbble-square</span></span></li>
<li className=""><Icon type="instagram" /><span className="anticon-class"><span className="ant-badge">instagram</span></span></li>
<li className=""><Icon type="yuque" /><span className="anticon-class"><span className="ant-badge">yuque</span></span></li>
</ul>

    </section>
  )
}

export default Section;
