// sidebar
export const SET_SIDEBAR_OPEN = "SET_SIDEBAR_OPEN";
export const SET_SIDEBAR_DOCKED = "SET_SIDEBAR_DOCKED";

//sidebar content
export const ON_SIDEBAR_CONTENT_EXPEND = "ON_SIDEBAR_CONTENT_EXPEND";

// layout
export const UPDATE_HEADER_HEIGHT = "UPDATE_HEADER_HEIGHT";