export const SET_SIDEBAR = "SET_SIDEBAR";
export const MEDIA_QUERY_CHANGED = "MEDIA_QUERY_CHANGED";
export const SET_SIDEBAR_OPEN = "SET_SIDEBAR_OPEN";
export const SET_SIDEBAR_DOCKED = "SET_SIDEBAR_DOCKED";